# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🛠️
      labels:
        - fix
    - title: Enhancements ✨
      labels:
        - enhancement
    - title: Breaking Changes 🔥
      labels:
        - breaking change
        - major update
    - title: Deprecations 🚧
      labels:
        - deprecation