services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: ".env.development"
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - DOCKER_LOCAL=true
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env.local
    profiles:
      - frontend-and-backend