<<<<<<< HEAD
import type { Metadata } from 'next'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { UserProvider } from '@/app/contexts/UserContext'
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/universal/sidebar/app-sidebar'
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@radix-ui/react-tooltip'
=======
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/universal/Navbar";
import { UserProvider } from "@/app/contexts/UserContext";
import { NextStepProvider, NextStep } from 'nextstepjs'
import CustomCard from "@/components/tutorial/Card";
import { steps } from "@/app/tutorial/steps";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
>>>>>>> 6c72c4d (inistal version of website tour)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
<<<<<<< HEAD
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                <div className="flex items-center gap-2 px-4">
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <SidebarTrigger className="-ml-1" />
                    </TooltipTrigger>
                    <TooltipContent side="right">
                      {/* TODO: fix tooltip styling (doesn't seem correct) */}
                      <p>⌘ /</p>        
                    </TooltipContent>
                  </Tooltip>
                </div>
              </header>
              {children}
              <Toaster />
            </SidebarInset>
          </SidebarProvider>
=======
          <NextStepProvider>
            <NextStep steps={steps} cardComponent={CustomCard}>
              <Navbar />
              {children}
              <Toaster />
            </NextStep>
          </NextStepProvider>

>>>>>>> 6c72c4d (inistal version of website tour)
        </UserProvider>
      </body>
    </html>
  )
}
