name: Deploy Frontend to Google Cloud Run

on:
  push:
    branches:
      - hotfix/will/debug-create-user

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_DEPLOYMENT_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: Create Artifact Registry Repository (if it doesn't exist)
        run: |
          gcloud artifacts repositories create pulse-frontend \
            --repository-format=docker \
            --location=${{ secrets.REGION }} \
            --description="Docker repository for pulse-frontend" || echo "Repository already exists."

      - name: Build Docker image for frontend
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/pulse-frontend/image-${{ github.sha }} .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/pulse-frontend/image-${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy pulse-frontend \
            --image "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/pulse-frontend/image-${{ github.sha }}" \
            --cpu-throttling \
            --min-instances 0 \
            --max-instances 10 \
            --region "${{ secrets.REGION }}"  \
            --platform managed \
            --allow-unauthenticated \
            --port 3000 \
            --set-env-vars GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}