name: Deploy Frontend to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

      # Step 4: Configure Docker to use gcloud as a credential helper
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker gcr.io --quiet


      # Step 5: Build Docker image for frontend
      - name: Build Docker image for frontend
        run: |
          docker build -t gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/frontend-app .

      # Step 6: Push Docker image to Google Container Registry
      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/frontend-app

      # Step 7: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend-app \
            --image "gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/frontend-app" \
            --region us-east4 \
            --platform managed \
            --allow-unauthenticated \
            --port 3000
