name: Check Other PR Dependencies on Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check Dependencies
    steps:
      - uses: gregsdennis/dependencies-action@1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}